// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SESMTTech.Gestor.PlanosDeAcao.Infrastructure.EntityFrameworkCore;

namespace SESMTTech.Gestor.PlanosDeAcao.Infrastructure.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(PlanosDeAcaoContext))]
    partial class PlanosDeAcaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SESMTTech.Gestor.PlanosDeAcao.Domain.Models.PlanoDeAcaoAggregate.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Acao");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("DataRealizacao");

                    b.Property<string>("Descricao");

                    b.Property<int>("Numero");

                    b.Property<Guid>("PlanoDeAcaoId");

                    b.Property<DateTime>("Prazo");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PlanoDeAcaoId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("SESMTTech.Gestor.PlanosDeAcao.Domain.Models.PlanoDeAcaoAggregate.PlanoDeAcao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ano");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(100);

                    b.Property<int>("Numero");

                    b.HasKey("Id");

                    b.HasIndex("Ano");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("PlanosDeAcao");
                });

            modelBuilder.Entity("SESMTTech.Gestor.PlanosDeAcao.Domain.Models.PlanoDeAcaoAggregate.Responsavel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<Guid>("ItemId");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("SESMTTech.Gestor.PlanosDeAcao.Domain.Models.PlanoDeAcaoAggregate.Item", b =>
                {
                    b.HasOne("SESMTTech.Gestor.PlanosDeAcao.Domain.Models.PlanoDeAcaoAggregate.PlanoDeAcao")
                        .WithMany("Itens")
                        .HasForeignKey("PlanoDeAcaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SESMTTech.Gestor.PlanosDeAcao.Domain.Models.PlanoDeAcaoAggregate.Responsavel", b =>
                {
                    b.HasOne("SESMTTech.Gestor.PlanosDeAcao.Domain.Models.PlanoDeAcaoAggregate.Item")
                        .WithMany("Responsaveis")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
